### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position...

### ISSUE THREAD

**Issue by Mr-x2020** [RandomRobbieBF/wp-file-manager#1]
![image](https://user-images.githubusercontent.com/65666323/92100517-6cef7d80-edcb-11ea-85ad-d20ce1f49336.png)
![image](https://user-images.githubusercontent.com/65666323/92100874-d96a7c80-edcb-11ea-8f90-c78e7c906b5e.png)

any solution for these two errors?

**Comment by RandomRobbieBF** [comment]
Tried with python3?

**Comment by Mr-x2020** [comment]
![image](https://user-images.githubusercontent.com/65666323/92124681-9de0aa00-eded-11ea-8a60-b8d46337fb5a.png)

**Comment by RandomRobbieBF** [comment]
Looks like a local language setting i think.

pull new version and see if that fix's it.
